### ISSUE TITLE
Wrong redirect for "Generates a structure, which has been preconfigured."

### ISSUE THREAD

**Issue by KristenStuffs** [alexsocha/luckyblockmod.com#5]
The link in https://www.luckyblockmod.com/docs/#/outcomes?id=structure (at the word preconfigured) redirects to  https://www.luckyblockmod.com/docs/#/config_files?id=structures instead of https://www.luckyblockmod.com/docs/#/?id=structurestxt.

**Comment by alexsocha** [comment]
Fixed
