### ISSUE TITLE
suggestion:add back the 1.12.2 and 1.8.9 template

### ISSUE THREAD

**Issue by Brandonbr1** [alexsocha/luckyblockmod.com#9]
@alexsocha 
Hi PlayerInDistress can you add back the 1.12.2 and 1.8.9 template because that is still a popular Minecraft version for lucky block addons because of loot++ so i can add custom drops

**Comment by alexsocha** [comment]
I wish I could, but the those templates are not in the git history of this project, and I've lost any other copy

**Comment by Brandonbr1** [comment]
> I wish I could, but the those templates are not in the git history of this project, and I've lost any other copy

@alexsocha  i found the 1.8 template
https://web.archive.org/web/20170929122844/http://www.minecraftascending.com/projects/lucky_block/documentation/6_1_add_ons.html
